### ISSUE TITLE
Dataset of the 2,686 approved excipients smile structure

### ISSUE THREAD

**Issue by ClinicalAI** [DanReker/CoAggregators#1]
Hello,
I couldn't find the smile structure of the 2,686 approved excipients you used to evaluate your work. There is a file gras_iig.tsv in repository but it has only 800 excipients.

https://github.com/DanReker/CoAggregators/blob/master/data/gras_iig.tsv

Could you please upload the whole excipients datasets.

Thanks,

**Comment by DanReker** [comment]
As noted in the paper, we define excipients here broadly, i.e. "excipients were selected from the FDA list of inactive ingredients, the FDA list of ‘generally recognized as safe’ ingredients, and other FDA-approved small molecules. "
This means to arrive at the larger excipient dataset, you need to combine GRAS & IGG (gras_iig.tsv) together with other approved small molecules (drugbank5_approved_names_smiles.tsv). Please note that there is some overlap between these two datasets and we need to remove self-aggregating drugs. The code to do all that is available at  https://github.com/DanReker/CoAggregators/blob/8bd0307bcb822f828fe23ce918fa12b78ee01661/machine%20learning/predict_pairs.py#L101-L124
